namespace WvWAnalyst.Contracts;

public sealed record HistoricalEffectivenessSnapshotDto(
    string MethodVersion,
    string GeneratedAtUtc,
    FightAnalysisSelectionDto Selection,
    HistoricalEffectivenessScopeDto Scope,
    HistoricalEffectivenessMethodologyDto Methodology,
    IReadOnlyList<HistoricalEffectivenessStratumDto> Strata,
    IReadOnlyList<HistoricalEffectivenessReportDto> Reports);

public sealed record HistoricalEffectivenessScopeDto(
    int FilteredFightCount,
    int CacheFightCount,
    int MissingCacheFightCount,
    int ObservationCount,
    int SquadPerspectiveObservationCount,
    int EnemyPerspectiveObservationCount,
    IReadOnlyList<string> AvailabilityNotes);

public sealed record HistoricalEffectivenessMethodologyDto(
    string Summary,
    string Weighting,
    string ConfidenceIntervals,
    string EvidenceScore,
    string AssociationScore,
    string Interpretation,
    int MinimumPairedFights,
    int TargetPairedFights);

public sealed record HistoricalEffectivenessStratumDto(
    string Type,
    string Key,
    string Label,
    int FilteredFightCount,
    int CacheFightCount);

public sealed record HistoricalEffectivenessReportDto(
    string Key,
    string PerspectiveSideId,
    string OpposingSideId,
    string OutcomeFamily,
    string OutcomeLabel,
    string BaselineLabel,
    int OutcomeObservationCount,
    int BaselineObservationCount,
    int OutcomeFightCount,
    int BaselineFightCount,
    int PairedFightCount,
    string ConfidenceLabel,
    IReadOnlyList<HistoricalEffectivenessMetricDto> Metrics,
    IReadOnlyList<HistoricalEffectivenessNamedEffectDto> NamedEffects);

public sealed record HistoricalEffectivenessMetricDto(
    string Key,
    string Label,
    string Group,
    string Unit,
    bool Available,
    string? UnavailableReason,
    double? OutcomeAverage,
    double? BaselineAverage,
    double? Difference,
    double? PercentLift,
    double? Lower95Difference,
    double? Upper95Difference,
    double? PositiveDifferenceFightPercent,
    double? DirectionConsistencyPercent,
    double? StandardizedDifference,
    int OutcomeObservationCount,
    int BaselineObservationCount,
    int OutcomeFightCount,
    int BaselineFightCount,
    int PairedFightCount,
    int NonTieFightCount,
    double EvidenceScore,
    double AssociationScore,
    string ConfidenceLabel,
    string DirectionLabel,
    string Detail);

public sealed record HistoricalEffectivenessNamedEffectDto(
    int? Rank,
    string Key,
    string Name,
    string EffectType,
    long EffectId,
    string Unit,
    bool EligibleForRanking,
    string RankingResult,
    double? OutcomeAverage,
    double? BaselineAverage,
    double? Difference,
    double? PercentLift,
    double? OutcomePresencePercent,
    double? BaselinePresencePercent,
    double? PresenceDifferencePoints,
    double? OutcomeSecondaryAverage,
    double? BaselineSecondaryAverage,
    string? SecondaryUnit,
    double? Lower95Difference,
    double? Upper95Difference,
    double? DirectionConsistencyPercent,
    int OutcomeObservationCount,
    int BaselineObservationCount,
    int PairedFightCount,
    int NonTieFightCount,
    double EvidenceScore,
    double AssociationScore,
    string ConfidenceLabel,
    string DirectionLabel,
    string Detail);

public sealed record HistoricalEffectivenessWinLossSnapshotDto(
    string MethodVersion,
    string GeneratedAtUtc,
    HistoricalEffectivenessScopeDto Wins,
    HistoricalEffectivenessScopeDto Losses,
    HistoricalEffectivenessWinLossMethodologyDto Methodology,
    IReadOnlyList<string> AvailabilityNotes,
    IReadOnlyList<HistoricalEffectivenessWinLossReportDto> Reports);

public sealed record HistoricalEffectivenessWinLossMethodologyDto(
    string Summary,
    string Comparison,
    string Weighting,
    string ConfidenceIntervals,
    string SeparationScore,
    string Interpretation,
    int MinimumPairedFights);

public sealed record HistoricalEffectivenessWinLossReportDto(
    string Key,
    string PerspectiveSideId,
    string OpposingSideId,
    string OutcomeFamily,
    string OutcomeLabel,
    string BaselineLabel,
    int WinPairedFightCount,
    int LossPairedFightCount,
    string ConfidenceLabel,
    IReadOnlyList<HistoricalEffectivenessWinLossMetricDto> Metrics,
    IReadOnlyList<HistoricalEffectivenessWinLossNamedEffectDto> NamedEffects);

public sealed record HistoricalEffectivenessWinLossMetricDto(
    int? Rank,
    string Key,
    string Label,
    string Group,
    string Unit,
    bool Available,
    string? UnavailableReason,
    double? WinOutcomeAverage,
    double? WinBaselineAverage,
    double? WinDifference,
    double? WinPercentLift,
    double? WinAssociationScore,
    double? WinEvidenceScore,
    double? LossOutcomeAverage,
    double? LossBaselineAverage,
    double? LossDifference,
    double? LossPercentLift,
    double? LossAssociationScore,
    double? LossEvidenceScore,
    double? ResultEdge,
    double? Lower95ResultEdge,
    double? Upper95ResultEdge,
    double? SeparationScore,
    double EvidenceScore,
    string ConfidenceLabel,
    string DirectionLabel,
    string RankingResult,
    string Detail);

public sealed record HistoricalEffectivenessWinLossNamedEffectDto(
    int? Rank,
    string Key,
    string Name,
    string EffectType,
    long EffectId,
    string Unit,
    bool Available,
    string? UnavailableReason,
    double? WinOutcomeAverage,
    double? WinBaselineAverage,
    double? WinDifference,
    double? WinPercentLift,
    double? WinAssociationScore,
    double? WinEvidenceScore,
    double? LossOutcomeAverage,
    double? LossBaselineAverage,
    double? LossDifference,
    double? LossPercentLift,
    double? LossAssociationScore,
    double? LossEvidenceScore,
    double? ResultEdge,
    double? Lower95ResultEdge,
    double? Upper95ResultEdge,
    double? SeparationScore,
    double EvidenceScore,
    string ConfidenceLabel,
    string DirectionLabel,
    string RankingResult,
    string Detail);
